version: 0.2

phases:
   install:
      runtime-versions:
         docker: 18

   pre_build:
      commands:
      - echo Logging in to Amazon ECR...
      - $(aws configure set aws_access_key_id  AKIA4QP5PZXMTOIXYKR7)
      - $(aws configure set aws_secret_access_key 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)
      - $(aws configure set default.region us-east-2)
      - $(aws ecr get-login --no-include-email --region $AWS_REGION)
      
   build:
      commands:
      - echo Build started on `date`
      - echo Building Java
      - cd CustomerService
      - mvn compile
      - mvn package
      - echo Building the Docker image...
      - docker build -t c10_pod-3-customer-ms .
      - docker tag c10_pod-3-customer-ms:latest 860061945305.dkr.ecr.us-east-2.amazonaws.com/c10_pod-3-customer-ms:latest

   post_build:
      commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 860061945305.dkr.ecr.us-east-2.amazonaws.com/c10_pod-3-customer-ms:latest
      - echo Writing definitions file
      - printf '[{"name":"customer-ms-container","imageUri":"%s"}]' 860061945305.dkr.ecr.us-east-2.amazonaws.com/c10_pod-3-customer-ms:latest > taskdefinition.json
      - cat taskdefinition.json
        
artifacts:
  files: 
    - CustomerService/taskdefinition.json
